spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/doctor-patient-rest-liquibase
    password: root
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
server:
  servlet:
    context-path: /api
dddd:
  app:
    jwtSecret: ddddSecretKey
    jwtExpirationMs: 86400000