spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/doctor-patient-rest
    password: root
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
server:
  servlet:
    context-path: /api