spring:
  servlet:
    multipart:
        max-file-size: 26214400
        max-request-size: 26214400
        file-size-threshold: 0B
        resolve-lazily: false
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/doctor-patient-rest-liquibase
    password: root
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
    dispatch-options-request: true
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  max-http-header-size: 26214400
  servlet:
    context-path: /api
    encoding:
      force: true
dddd:
  app:
    jwtSecret: ddddSecretKey
    jwtExpirationMs: 86400000